### ISSUE TITLE
VCF input and suggestions

### ISSUE THREAD

**Issue by fgvieira** [Zilong-Li/PCAone#2]
Hi Zilong,

I was quite interested in `PCAone`, since it supports several different algorithms and optimizations.

However, as with [pcangsd](https://github.com/Rosemeis/pcangsd/issues/59#issue-1119905019), I feel the main drawback is that they do not support VCF files directly. Are there any plans to support VCF input? It would be nice if it would support genotypes, and both the GL and PL likelihoods (since different callers use different formats).

And maybe expand the `Usage` on the format of the output file and how you can make a plot out of it. Is it the same format as `pcangsd`?

thanks,

PS - if your plan is to have it be a standard for bio/popgen research, it could be a good idea to add it to `bioconda`. 😄

**Comment by Zilong-Li** [comment]
Hi, Filipe

Thanks for your kind useful suggestions and interest in PCAone!

In general, PCAone is designed to be able to support any file format as long as implementing a parser of that file. So It should be straightforward to support VCF! Since VCF can be easily converted to any other data formats by the awesome bcftools, I am not currently working on supporting VCF. But I will consider supporting it after the manuscript of PCAone is done first. Regarding PCAngsd, Jonas and me are considering refactor and optimize the algorithm. Will support vcf probably after we upgrading it.  

Yes, I will document the `PCAone Usage` more properly. And of course it is a good idea to add it to `bioconda`. Already started writing a recipe. 

Stay tuned!

**Comment by fgvieira** [comment]
Hi Zilong-Li,

thanks for your quick reply, and good to know that VCF will be supported somehow in the near future.

I agree, no point in reinventing the wheel, maybe if there was a way to convert a VCF file to (e.g.) beagle with `bcftools`.

cheers,
